### PR TITLE
Fix goroutine and connection leak on database connect

### LINKED ISSUE #58: Goroutine leak on database connect
The goroutine detector in my project detected a goroutine leak when I started using this library. I think I found the leak location - it's not closed connections here:

https://github.com/fergusstrange/embedded-postgres/blob/master/prepare_database.go#L66

and

https://github.com/fergusstrange/embedded-postgres/blob/master/prepare_database.go#L107

### PR DESCRIPTION
**Pull request by EldarKurbanov**
Closes #58 

I also added a goroutine leak detector to prevent unclosed connections in the future and one exception for goroutine leak detector, since I did not find how to fix it.

### CODE REVIEW

**Comment by EldarKurbanov** [comment]
CI didn't like my go.sum. How can I fix it?

**Comment by fergusstrange** [comment]
Hey @EldarKurbanov you'll need to run `go mod tidy` in the top level module and each of sub modules to clean up the go.sum files.

Regarding the test coverage changes I'd imagine you probably only need to verify no leak in one of the top level tests as they cover almost all the code and run on every operating system.

**Comment by EldarKurbanov** [comment]
Do you mean that I need to leave the goroutine leak check in only one test?

**Comment by fergusstrange** [comment]
Hi @EldarKurbanov apologies for the delay.

Yes I suggest this is probably only actually needed inline inside the `Test_DefaultConfig` test as it should cover most lines of code already.

We also should attempt to keep the coverage above 90% as a general rule project so users can be confident from a glance we're reliable. Is there anything you can do to get those extra lines you've added covered?

**Comment by EldarKurbanov** [comment]
I would really be very happy if you could tell me how I can check my added code that close the connection to the database.

The only one the way I see for increase test coverage is by adding a mock to the database connection. I can do it if there are no better ideas and no one will mind.

**Comment by EldarKurbanov** [comment]
I removed `defer verifyLeak(t)` as you suggested and left it only in Test_DefaultConfig.

**Comment by fergusstrange** [comment]
Looks much better! I think you're correct maybe wrapping `db := sql.OpenDB` in a func and passing that into these methods, or utilising a new interface that wraps up these responsibilities would be the best way forward.

**Comment by EldarKurbanov** [comment]
Thank you for your suggestion! But I found an easier way to test the database connection closing code, wrote a test for it, and the coverage increased. I would be very glad to hear your opinion about the rewritten code.

**Review by fergusstrange — APPROVED** [review]

**Comment by fergusstrange** [comment]
Hey @EldarKurbanov sorry this has taken so long! I needed some bandwidth to get my head around your changes. They make sense to me now. I may try and clean up a little in the next few releases to align better with the style of the rest of the code, and make the tests a little more verbose, but functionally this looks great.

Thanks for your contribution and hopefully this helps resolve your issues!

**Pull request merged**
