### PR TITLE
Add error info in message 'unable to init db'

### LINKED ISSUE #78: Add error info when 'unable to init db'
Currently, I get this error, without any useful information:
```
panic: localpg: failed to start PgSQL: unable to init database using: /tmp/go_embedded_pgsql_binaries_3773798719/bin/initdb -A password -U username -D /tmp/go_embedded_pgsql_runtime_2105005878/data --pwfile=/tmp/go_embedded_pgsql_runtime_2105005878/pwfile --locale=en_US.UTF-8
```

### PR DESCRIPTION
**Pull request by dor-utila**
Fixes #78

### CODE REVIEW

**Comment by fergusstrange** [comment]
Hey @dor-utila, happy to merge this in once you've fixed up tests.

Looks like you're using a package not included in the current dependencies.

**Comment by fergusstrange** [comment]
Great stuff, I'll release this shortly once I've done some sanity tests locally.

**Comment by mackinleysmith** [comment]
Hey y'all, is this ready for release by any chance? We would benefit quite a bit from it, as we run into some difficult to debug errors locally on macOS.

**Comment by fergusstrange** [comment]
@mackinleysmith apologies I totally forgot to actually release this!

Released [here ](https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.18.0).

**Comment by mackinleysmith** [comment]
Thanks so much!!

**Pull request merged**
