### PR TITLE
Cachepath

### PR DESCRIPTION
**Pull request by movit**
We want to use embedded-postgress in our CI/CD process. For this purpose we need to control every  place where files are resides. CacheLocation was only place what can't be configured at startup time. This PR fix this issue.

### CODE REVIEW

**Comment by movit** [comment]
@fergusstrange Could you please take look to this PR?

**Comment by movit** [comment]
@fergusstrange Could you please take look to this PR?

**Review by fergusstrange — APPROVED** [review]

**Comment by fergusstrange** [comment]
Good stuff @movit, I'll get this merged and released shortly.

**Comment by fergusstrange** [comment]
[Released v1.24.0](https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.24.0) @movit

**Pull request merged**
