### PR TITLE
Replace xz library with newer one

### PR DESCRIPTION
**Pull request by der-eismann**
Reasoning:
- Last commit in this repo was 7 years ago, project is dead
- It's not versioned and doesn't have a go.mod
- License can't be detected by pkg.go.dev & other tools
- Causes [pkg.go.dev](https://pkg.go.dev/github.com/xi2/xz) to not show any documentation
- Tools that check for license compliance might fail on embedded-postgres because it pulls in github.com/xi2/xz

### CODE REVIEW

**Comment by fergusstrange** [comment]
Awesome @der-eismann, would be be a great upgrade.

**Comment by Araoz-Lucas-bah** [comment]
can we move forward with this change? I want to include this in one of my projects, but the license check tooling is failing on this exact thing

**Comment by der-eismann** [comment]
Unfortunately I have no idea why the tests on Windows and macOS are failing, I can't reproduce it here.

**Comment by fergusstrange** [comment]
Hmmm this is interesting @der-eismann. I can confirm your changes pass locally with an M2 Macbook. Perhaps try boosting the windows/mac build runners to see if you have any luck here?

**Pull request closed without merging**
