### PR TITLE
⭐️ use amd64 postgres on arm64 macOS

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Review by fergusstrange — APPROVED** [review]
This looks good although tricky to test. Nothing from Circle or Github that provides any automated OSX arm64 testing.

Any ideas for this?

**Comment by chris-rock** [comment]
I am unsure, I tested this locally. I think it will be tricky until github has proper support for arm macs. https://github.com/actions/runner/issues/805

**Comment by fergusstrange** [comment]
Yeah okay fair enough. I think I'll rework `defaultVersionStrategy` in order to pass in the os and arch in the future. At this point we can add coverage for this behaviour.

I'll merge and if you fancy tackling the above to make this block a little more testable please feel free to open another PR. 

Great work!

**Comment by chris-rock** [comment]
I think the intuitive behavior is to allow users to override the version strategy. This would allow this lib to focus on the core features and leave users the option to override if necessary

**Comment by fergusstrange** [comment]
@chris-rock I'll add you to review the next pull request around the suggested changes then if you're interested?

In the meantime I've published a [release](https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.7.0) for your changes.

**Comment by chris-rock** [comment]
@fergusstrange thank you very much! Yeah, I am happy to help.

**Pull request merged**
