### PR TITLE
version strategy: zonkio's arm arch name are different from GOOARCH

### PR DESCRIPTION
**Pull request by bearsh**
on arm (32bit), use 'uname -m' to get the excact arm version

### CODE REVIEW

**Comment by bearsh** [comment]
regarding tests, AFAIK there's no easy way to setup a github action which runs on arm...

**Comment by fergusstrange** [comment]
First of all apologies @bearsh this totally slipped me by.

I had a look into adding a CircleCI/Travis build that will be able to run the platform-tests on ARM, which I think is a must if we're going to claim support. I'm happy to have a play around with this but it may take me a little while. In the meantime see if you can get the build up and running mimicking the same behaviour as the Github Actions platform-test build?

Thanks

**Comment by fergusstrange** [comment]
Hey @bearsh I've added some CircleCI tests for arm64 though there's no coverage for arm32. Can you rebase off this branch and see if the tests pass?

If we can get that coverage at least I'll merge in.

Thanks!

**Comment by bearsh** [comment]
mmh it seems simply force push doesn't add the new tests to this PR

**Comment by fergusstrange** [comment]
Urgh. I'll merge as is and we'll fix this up on master after we have a build to work from.

**Comment by fergusstrange** [comment]
Looks like we got a green build first hit @bearsh https://app.circleci.com/pipelines/github/fergusstrange/embedded-postgres/8/workflows/5735b0b4-0712-47a6-bcd9-f447924decc8/jobs/12

Great work! As mentioned in https://github.com/fergusstrange/embedded-postgres/pull/26 I may look to rework the version strategy to get some coverage in there now we have some more complex logic.

If you fancy a crack at this feel free to chip in and happy to work with you / review more PRs.

**Comment by fergusstrange** [comment]
[Release](https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.7.0) published with your changes @bearsh.

**Pull request merged**
