### PR TITLE
Add logger to config.

### LINKED ISSUE #11: Add custom logger for postgres output

### PR DESCRIPTION
**Pull request by onrik**
Closes #11

### CODE REVIEW

**Comment by fergusstrange** [comment]
Hey @onrik this looks great.

As part of this PR could you add the config directive to the documentation table and examples in the README.md and also add the custom config line to the [`func Test_CustomConfig(t *testing.T)`](https://github.com/fergusstrange/embedded-postgres/blob/d972fc361ba83c184cbc0689b35228cf0e5ecde7/embedded_postgres_test.go#L232) perhaps with `ioutil.Discard`. This should help bump coverage which has currently dropped a little.

It might also be worth highlighting that using `ioutil.Discard` is the easiest way to turn off logging in the README.md as well.

All in all great stuff though and ready to merge when these changes are in! 👏

**Comment by onrik** [comment]
With `ioutil.Discard` tests still failed :(

**Comment by fergusstrange** [comment]
Hey @onrik my apologies it turns out there are some issues with using Discard. The recommended approach is actually to use `Logger(nil)` according to `exec.Command`.

This was being hidden behind some bad code in `shutdownDBAndFail` which I've [updated](https://github.com/fergusstrange/embedded-postgres/commit/e99c651b4015a7e9aecdde5fd10a3c3b68555b4b).

Suggest that we update to a convenience method called `Silent` or something akin in order to wrap up the `Logger(nil)` call. Then just a matter of updating docs to reflect this and we're good to go!

Apologies again for the bad advice!

**Review by fergusstrange — APPROVED** [review]
Preference would be to add a convenience method but we can have a look at that as a next step.

Great work and merging now!

**Pull request merged**
